# Generated by Django 3.2.7 on 2026-01-12 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water_quality', '0002_prediction'),
    ]

    operations = [
        migrations.AddField(
            model_name='regtable',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
